const translations = {
    en: {
        nav_studio: "Studio",
        nav_expertise: "Expertise",
        nav_works: "Works",
        nav_pricing: "Pricing",
        nav_faq: "FAQ",
        nav_talk: "Let's Talk",
        
        hero_badge: "Global Partners",
        hero_title_1: "Digital",
        hero_title_2: "Excellence",
        hero_desc: "We craft premium digital infrastructure and luxury digital experiences that elevate brands globally.",
        hero_btn: "Start a Project",
        
        about_label: "Studio Philosophy",
        about_text: "We believe the web should be flawless. We strip away the unnecessary and focus entirely on creating sophisticated, ultra-smooth platforms that perform perfectly on every device.",
        
        works_title: "Selected<br>Works",
        works_view_all: "View All Projects",
        work_1_title: "House of Burger",
        work_1_cat: "Restaurant E-commerce",
        work_1_desc: "A modern restaurant website featuring online burger ordering, an interactive menu showcase, and promotional campaigns designed to enhance the customer dining experience.",
        work_1_badge_1: "Web App",
        work_1_badge_2: "E-commerce",
        work_2_title: "Imaji Digital",
        work_2_cat: "Digital Agency",
        work_2_desc: "A premium digital agency landing page showcasing 3D products, immersive AR experiences, and creative digital solutions through a modern, conversion-focused design.",
        work_2_badge_1: "Landing Page",
        work_2_badge_2: "3D/AR",
        work_3_title: "SchoolCMS",
        work_3_cat: "Educational Platform",
        work_3_desc: "A comprehensive school platform providing announcements, news, galleries, events, and institutional information through an intuitive and responsive interface.",
        work_3_badge_1: "CMS",
        work_3_badge_2: "Web App",
        work_4_title: "Personal Portfolio",
        work_4_cat: "Portfolio Website",
        work_4_desc: "A modern portfolio website showcasing creativity, technical expertise, and personal branding through a minimalist and responsive design.",
        work_4_badge_1: "Portfolio",
        work_4_badge_2: "Web Design",
        works_view_more: "View More Projects",
        works_view_less: "View Less",
        work_view: "View",

        // Expertise / Services
        expertise_title: "Engineering Expertise",
        exp_1_title: "Digital Strategy",
        exp_1_sub: "Architecture, Planning & Discovery",
        exp_2_title: "UI/UX Design Systems",
        exp_2_sub: "Tokenized Interfaces & Interactions",
        exp_3_title: "Web Application Engineering",
        exp_3_sub: "Scalable React & Next.js Platforms",
        exp_4_title: "Backend & API Orchestration",
        exp_4_sub: "Secure, High-Performance Servers",

        // Metrics
        metrics_delivered: "Enterprise Projects Delivered",
        metrics_satisfaction: "Client Satisfaction Rate",
        metrics_years: "Years of Experience",

        // Pipeline
        pipeline_title: "Our Pipeline",
        pipeline_desc: "A methodical, precision-engineered workflow ensuring flawless execution from initial discovery to final deployment.",
        proc_1_title: "Discovery & Strategy",
        proc_1_desc: "Deep analysis of requirements, architectural mapping, and defining clear, actionable success metrics.",
        proc_2_title: "Design Systems",
        proc_2_desc: "Crafting bespoke user interfaces, tokenized design elements, and fluid micro-interactions.",
        proc_3_title: "Engineering",
        proc_3_desc: "Writing immaculate, scalable codebase using modern frameworks, ensuring blistering fast load times.",
        proc_4_title: "QA & Launch",
        proc_4_desc: "Rigorous multi-device performance auditing followed by a seamless platform deployment.",

        // Pricing
        pricing_label: "Investment",
        pricing_title: "Transparent Pricing",
        pricing_tab_1: "Landing Page",
        pricing_tab_2: "Company Profile",
        pricing_tab_3: "E-Commerce",
        pricing_tab_4: "Portfolio Website",
        
        price_tier_1: "Essential",
        price_tier_1_desc_landing: "A high-conversion entry point with foundational design and perfect performance.",
        price_tier_1_desc_profile: "A professional company profile to build trust and display your services.",
        price_tier_1_desc_ecommerce: "A clean online store setup for up to 30 products with WhatsApp checkout.",
        price_tier_1_desc_portfolio: "A clean and modern portfolio website designed to showcase your work and personal brand professionally.",
        price_tier_2: "Professional",
        price_tier_2_desc_landing: "Our complete pipeline. Strategic UX, complex layouts, and dynamic animations.",
        price_tier_2_desc_profile: "Advanced company profile with a news/blog section, search, and dynamic galleries.",
        price_tier_2_desc_ecommerce: "Full-scale e-commerce with payment gateways, admin dashboard, and order management.",
        price_tier_2_desc_portfolio: "A premium portfolio experience crafted to impress clients, recruiters, and potential collaborators.",
        price_tier_2_badge: "Most Popular",
        price_tier_3: "Enterprise",
        price_tier_3_desc_landing: "Tailor-made structural engineering for massive scale and complex backend integrations.",
        price_tier_3_desc_profile: "Enterprise profile with multi-language support, custom integrations, and priority support.",
        price_tier_3_desc_ecommerce: "Enterprise e-commerce with multi-role dashboards, sales analytics, and advanced security.",
        price_tier_3_desc_portfolio: "A fully customized portfolio website built for professionals who want to stand out with premium interactions and advanced functionality.",
        price_inquire: "Inquire Now",

        // Portfolio Benefits - Tier 1
        t1_port_1: "1 Responsive Portfolio",
        t1_port_2: "Up to 5 Projects",
        t1_port_3: "About Me Section",
        t1_port_4: "Contact Form",
        t1_port_5: "Social Media Links",
        t1_port_6: "Mobile Responsive",
        t1_port_7: "Basic SEO",
        t1_port_8: "2 Revisions",

        // Portfolio Benefits - Tier 2
        t2_port_1: "Everything in Essential",
        t2_port_2: "Up to 15 Projects",
        t2_port_3: "Custom UI Design",
        t2_port_4: "Smooth Scroll Animations",
        t2_port_5: "Project Detail Pages",
        t2_port_6: "Skills Section",
        t2_port_7: "Testimonials",
        t2_port_8: "Resume / CV Download",
        t2_port_9: "Contact Form",
        t2_port_10: "Google Analytics",
        t2_port_11: "Speed Optimization",
        t2_port_12: "5 Revisions",

        // Portfolio Benefits - Tier 3
        t3_port_1: "Unlimited Projects",
        t3_port_2: "Fully Custom Design",
        t3_port_3: "CMS Integration",
        t3_port_4: "Blog / Articles",
        t3_port_5: "Case Study Pages",
        t3_port_6: "Dark & Light Mode",
        t3_port_7: "Multi-language Ready",
        t3_port_8: "Advanced SEO",
        t3_port_9: "Analytics Dashboard",
        t3_port_10: "Priority Support",
        t3_port_11: "Unlimited Minor Revisions",

        // Tier 1 Benefits
        t1_l1: "1 Responsive Landing Page", t1_l2: "Premium UI Design", t1_l3: "Mobile & Tablet Optimized",
        t1_l4: "Contact Form", t1_l5: "WhatsApp Integration", t1_l6: "Basic SEO",
        t1_l7: "Fast Loading", t1_l8: "2 Revisions",
        t1_p1: "Up to 5 Pages", t1_p2: "Responsive Design", t1_p3: "Company Information",
        t1_p4: "Services Section", t1_p5: "Contact Form", t1_p6: "WhatsApp Button",
        t1_p7: "Basic SEO", t1_p8: "2 Revisions",
        t1_e1: "Up to 30 Products", t1_e2: "Shopping Cart", t1_e3: "Checkout",
        t1_e4: "Product Categories", t1_e5: "Responsive Design", t1_e6: "WhatsApp Checkout",
        t1_e7: "Basic SEO", t1_e8: "2 Revisions",

        // Tier 2 Benefits
        t2_l1: "Everything in Essential", t2_l2: "Custom UI/UX Design", t2_l3: "Advanced Animations",
        t2_l4: "Multiple Sections", t2_l5: "Lead Generation Form", t2_l6: "Google Maps Integration",
        t2_l7: "Speed Optimization", t2_l8: "On-page SEO", t2_l9: "Free Deployment", t2_l10: "5 Revisions",
        t2_p1: "Everything in Essential", t2_p2: "Up to 10 Pages", t2_p3: "Custom UI Design",
        t2_p4: "Gallery", t2_p5: "News / Blog", t2_p6: "Google Maps",
        t2_p7: "Speed Optimization", t2_p8: "SEO Ready", t2_p9: "Free Deployment", t2_p10: "5 Revisions",
        t2_e1: "Everything in Essential", t2_e2: "Unlimited Products", t2_e3: "Payment Gateway Integration",
        t2_e4: "Customer Accounts", t2_e5: "Order Management", t2_e6: "Inventory Management",
        t2_e7: "Discount Coupons", t2_e8: "Admin Dashboard", t2_e9: "Speed Optimization",
        t2_e10: "Free Deployment", t2_e11: "5 Revisions",

        // Tier 3 Benefits
        t3_l1: "Everything in Professional", t3_l2: "Premium Motion Effects", t3_l3: "Custom Illustrations",
        t3_l4: "CMS Integration", t3_l5: "Blog Section", t3_l6: "Analytics Setup",
        t3_l7: "Priority Support", t3_l8: "10 Revisions",
        t3_p1: "Unlimited Pages", t3_p2: "Custom Features", t3_p3: "Admin Dashboard",
        t3_p4: "Dynamic Content", t3_p5: "Career Page", t3_p6: "Multi-language Ready",
        t3_p7: "Advanced SEO", t3_p8: "Analytics Integration", t3_p9: "Priority Support", t3_p10: "10 Revisions",
        t3_e1: "Everything in Professional", t3_e2: "Multi-role Dashboard", t3_e3: "Sales Reports",
        t3_e4: "Product Variants", t3_e5: "Shipping Integration", t3_e6: "Email Notifications",
        t3_e7: "Advanced Security", t3_e8: "Analytics Dashboard", t3_e9: "Priority Support", t3_e10: "10 Revisions",

        // FAQ
        faq_label: "Inquiries",
        faq_title: "Common Questions",
        faq_desc: "Everything you need to know about our process, timelines, and deliverables.",
        faq_1_q: "How long does a typical project take?",
        faq_1_a: "Our end-to-end pipeline typically requires 8 to 12 weeks. This ensures ample time for rigorous discovery, pixel-perfect design, robust engineering, and multi-device QA testing without compromising quality.",
        faq_2_q: "Do you work with startups or just enterprises?",
        faq_2_a: "We collaborate with both. Whether you are a Series-A startup aiming to establish a commanding presence or an enterprise seeking architectural modernization, our solutions scale to your structural needs.",
        faq_3_q: "What technologies do you use?",
        faq_3_a: "Our primary stack for performance and flexibility is React (Next.js), Tailwind CSS, GSAP for fluid animations, and robust backend solutions like Node.js or Laravel depending on API requirements.",
        faq_4_q: "Can you redesign an existing product?",
        faq_4_a: "Yes. We frequently audit and overhaul legacy platforms, improving their conversion rates, user retention, and overall aesthetic to align with modern luxury standards.",

        // CTA
        cta_title_1: "Let's Build",
        cta_title_2: "Together",
        
        // Footer
        footer_desc: "Elevating modern brands through superior digital design and architecture.",
        footer_menu: "Menu",
        footer_socials: "Socials",
        footer_location: "Location",
        footer_loc_text: "Global Remote Team<br>Operating across GMT to PST.",
        footer_time: "Local Time:",
        footer_rights: "© 2026 DKS Studio. All rights reserved.",
        footer_privacy: "Privacy Policy",
        footer_terms: "Terms of Service"
    },
    id: {
        nav_studio: "Studio",
        nav_expertise: "Keahlian",
        nav_works: "Karya",
        nav_pricing: "Harga",
        nav_faq: "FAQ",
        nav_talk: "Mulai Diskusi",
        
        hero_badge: "Mitra Global",
        hero_title_1: "Digital",
        hero_title_2: "Ekselensi",
        hero_desc: "Kami merancang infrastruktur digital premium dan pengalaman digital mewah yang mengangkat kelas merek Anda di dunia global.",
        hero_btn: "Mulai Proyek",
        
        about_label: "Filosofi Studio",
        about_text: "Kami percaya website harus tampil sempurna. Kami membuang semua yang tidak perlu dan sepenuhnya berfokus menciptakan platform canggih, sangat mulus, dan bekerja sempurna di segala perangkat.",
        
        works_title: "Karya<br>Pilihan",
        works_view_all: "Lihat Semua Proyek",
        work_1_title: "House of Burger",
        work_1_cat: "E-commerce Restoran",
        work_1_desc: "Website restoran modern yang menampilkan pemesanan burger online, tampilan menu interaktif, dan kampanye promosi yang dirancang untuk meningkatkan pengalaman bersantap pelanggan.",
        work_1_badge_1: "Aplikasi Web",
        work_1_badge_2: "E-commerce",
        work_2_title: "Imaji Digital",
        work_2_cat: "Agensi Digital",
        work_2_desc: "Landing page agensi digital premium yang menampilkan produk 3D, pengalaman AR imersif, dan solusi digital kreatif melalui desain modern yang berfokus pada konversi.",
        work_2_badge_1: "Landing Page",
        work_2_badge_2: "3D/AR",
        work_3_title: "SchoolCMS",
        work_3_cat: "Platform Pendidikan",
        work_3_desc: "Platform sekolah komprehensif yang menyediakan pengumuman, berita, galeri, acara, dan informasi institusional melalui antarmuka yang intuitif dan responsif.",
        work_3_badge_1: "CMS",
        work_3_badge_2: "Aplikasi Web",
        work_4_title: "Portofolio Pribadi",
        work_4_cat: "Situs Portofolio",
        work_4_desc: "Website portofolio modern yang menampilkan kreativitas, keahlian teknis, dan personal branding melalui desain minimalis dan responsif.",
        work_4_badge_1: "Portofolio",
        work_4_badge_2: "Desain Web",
        works_view_more: "Lihat Proyek Lainnya",
        works_view_less: "Lihat Lebih Sedikit",
        work_view: "Lihat",

        // Keahlian / Layanan
        expertise_title: "Keahlian Rekayasa",
        exp_1_title: "Strategi Digital",
        exp_1_sub: "Arsitektur, Perencanaan & Riset",
        exp_2_title: "Sistem Desain UI/UX",
        exp_2_sub: "Antarmuka Terstruktur & Interaktif",
        exp_3_title: "Rekayasa Aplikasi Web",
        exp_3_sub: "Platform React & Next.js yang Skalabel",
        exp_4_title: "Backend & Orkestrasi API",
        exp_4_sub: "Server Aman & Berkinerja Tinggi",

        // Metrik
        metrics_delivered: "Proyek Perusahaan Diselesaikan",
        metrics_satisfaction: "Tingkat Kepuasan Klien",
        metrics_years: "Tahun Pengalaman",

        // Alur Kerja
        pipeline_title: "Alur Kerja Kami",
        pipeline_desc: "Alur kerja metodis dan presisi yang memastikan eksekusi sempurna dari riset awal hingga peluncuran akhir.",
        proc_1_title: "Riset & Strategi",
        proc_1_desc: "Analisis mendalam kebutuhan, pemetaan arsitektur, dan penetapan metrik keberhasilan yang jelas.",
        proc_2_title: "Sistem Desain",
        proc_2_desc: "Merancang antarmuka pengguna bespoke, elemen desain terstruktur, dan interaksi mikro yang mengalir.",
        proc_3_title: "Rekayasa",
        proc_3_desc: "Menulis kode yang bersih dan skalabel menggunakan framework modern, memastikan waktu muat yang sangat cepat.",
        proc_4_title: "QA & Peluncuran",
        proc_4_desc: "Audit performa multi-perangkat yang ketat diikuti dengan peluncuran platform yang mulus.",

        // Harga
        pricing_label: "Investasi",
        pricing_title: "Harga Transparan",
        pricing_tab_1: "Landing Page",
        pricing_tab_2: "Company Profile",
        pricing_tab_3: "E-Commerce",
        pricing_tab_4: "Situs Portofolio",
        
        price_tier_1: "Esensial",
        price_tier_1_desc_landing: "Titik awal dengan konversi tinggi, desain mendasar, dan performa sempurna.",
        price_tier_1_desc_profile: "Profil perusahaan profesional untuk membangun kepercayaan dan menampilkan layanan Anda.",
        price_tier_1_desc_ecommerce: "Toko online bersih untuk maksimal 30 produk dengan checkout WhatsApp.",
        price_tier_1_desc_portfolio: "Website portofolio yang bersih dan modern yang dirancang untuk menampilkan karya dan personal brand Anda secara profesional.",
        price_tier_2: "Profesional",
        price_tier_2_desc_landing: "Alur kerja lengkap kami. Strategi UX, tata letak kompleks, dan animasi dinamis.",
        price_tier_2_desc_profile: "Profil perusahaan canggih dengan bagian berita/blog, pencarian, dan galeri dinamis.",
        price_tier_2_desc_ecommerce: "E-commerce skala penuh dengan gateway pembayaran, dasbor admin, dan manajemen pesanan.",
        price_tier_2_desc_portfolio: "Pengalaman portofolio premium yang dibuat untuk mengesankan klien, perekrut, dan calon kolaborator.",
        price_tier_2_badge: "Paling Populer",
        price_tier_3: "Perusahaan",
        price_tier_3_desc_landing: "Rekayasa struktural yang dibuat khusus untuk skala besar dan integrasi backend yang kompleks.",
        price_tier_3_desc_profile: "Profil perusahaan enterprise dengan dukungan multi-bahasa, integrasi kustom, dan dukungan prioritas.",
        price_tier_3_desc_ecommerce: "E-commerce perusahaan dengan dasbor multi-peran, analitik penjualan, dan keamanan tingkat lanjut.",
        price_tier_3_desc_portfolio: "Website portofolio yang sepenuhnya disesuaikan untuk profesional yang ingin tampil menonjol dengan interaksi premium dan fungsi lanjutan.",
        price_inquire: "Hubungi Kami",

        // Portfolio Benefits - Tier 1
        t1_port_1: "1 Portofolio Responsif",
        t1_port_2: "Hingga 5 Proyek",
        t1_port_3: "Bagian Tentang Saya",
        t1_port_4: "Formulir Kontak",
        t1_port_5: "Tautan Media Sosial",
        t1_port_6: "Responsif Seluler",
        t1_port_7: "SEO Dasar",
        t1_port_8: "2 Revisi",

        // Portfolio Benefits - Tier 2
        t2_port_1: "Semua di Paket Esensial",
        t2_port_2: "Hingga 15 Proyek",
        t2_port_3: "Desain UI Kustom",
        t2_port_4: "Animasi Scroll Mulus",
        t2_port_5: "Halaman Detail Proyek",
        t2_port_6: "Bagian Keahlian",
        t2_port_7: "Testimoni",
        t2_port_8: "Unduh Resume / CV",
        t2_port_9: "Formulir Kontak",
        t2_port_10: "Google Analytics",
        t2_port_11: "Optimasi Kecepatan",
        t2_port_12: "5 Revisi",

        // Portfolio Benefits - Tier 3
        t3_port_1: "Proyek Tanpa Batas",
        t3_port_2: "Desain Sepenuhnya Kustom",
        t3_port_3: "Integrasi CMS",
        t3_port_4: "Blog / Artikel",
        t3_port_5: "Halaman Studi Kasus",
        t3_port_6: "Mode Gelap & Terang",
        t3_port_7: "Siap Multi-bahasa",
        t3_port_8: "SEO Tingkat Lanjut",
        t3_port_9: "Dasbor Analitik",
        t3_port_10: "Dukungan Prioritas",
        t3_port_11: "Revisi Minor Tanpa Batas",

        // Benefit Tier 1
        t1_l1: "1 Halaman Landing Responsif", t1_l2: "Desain UI Premium", t1_l3: "Dioptimalkan untuk Mobile & Tablet",
        t1_l4: "Formulir Kontak", t1_l5: "Integrasi WhatsApp", t1_l6: "SEO Dasar",
        t1_l7: "Loading Cepat", t1_l8: "2 Revisi",
        t1_p1: "Hingga 5 Halaman", t1_p2: "Desain Responsif", t1_p3: "Informasi Perusahaan",
        t1_p4: "Bagian Layanan", t1_p5: "Formulir Kontak", t1_p6: "Tombol WhatsApp",
        t1_p7: "SEO Dasar", t1_p8: "2 Revisi",
        t1_e1: "Hingga 30 Produk", t1_e2: "Keranjang Belanja", t1_e3: "Checkout",
        t1_e4: "Kategori Produk", t1_e5: "Desain Responsif", t1_e6: "Checkout via WhatsApp",
        t1_e7: "SEO Dasar", t1_e8: "2 Revisi",

        // Benefit Tier 2
        t2_l1: "Semua di Paket Esensial", t2_l2: "Desain UI/UX Kustom", t2_l3: "Animasi Tingkat Lanjut",
        t2_l4: "Banyak Seksi", t2_l5: "Formulir Lead Generation", t2_l6: "Integrasi Google Maps",
        t2_l7: "Optimasi Kecepatan", t2_l8: "SEO On-page", t2_l9: "Deployment Gratis", t2_l10: "5 Revisi",
        t2_p1: "Semua di Paket Esensial", t2_p2: "Hingga 10 Halaman", t2_p3: "Desain UI Kustom",
        t2_p4: "Galeri", t2_p5: "Berita / Blog", t2_p6: "Google Maps",
        t2_p7: "Optimasi Kecepatan", t2_p8: "Siap SEO", t2_p9: "Deployment Gratis", t2_p10: "5 Revisi",
        t2_e1: "Semua di Paket Esensial", t2_e2: "Produk Tanpa Batas", t2_e3: "Integrasi Payment Gateway",
        t2_e4: "Akun Pelanggan", t2_e5: "Manajemen Pesanan", t2_e6: "Manajemen Inventaris",
        t2_e7: "Kupon Diskon", t2_e8: "Dasbor Admin", t2_e9: "Optimasi Kecepatan",
        t2_e10: "Deployment Gratis", t2_e11: "5 Revisi",

        // Benefit Tier 3
        t3_l1: "Semua di Paket Profesional", t3_l2: "Efek Gerak Premium", t3_l3: "Ilustrasi Kustom",
        t3_l4: "Integrasi CMS", t3_l5: "Bagian Blog", t3_l6: "Pengaturan Analitik",
        t3_l7: "Dukungan Prioritas", t3_l8: "10 Revisi",
        t3_p1: "Halaman Tanpa Batas", t3_p2: "Fitur Kustom", t3_p3: "Dasbor Admin",
        t3_p4: "Konten Dinamis", t3_p5: "Halaman Karir", t3_p6: "Siap Multi-bahasa",
        t3_p7: "SEO Tingkat Lanjut", t3_p8: "Integrasi Analitik", t3_p9: "Dukungan Prioritas", t3_p10: "10 Revisi",
        t3_e1: "Semua di Paket Profesional", t3_e2: "Dasbor Multi-peran", t3_e3: "Laporan Penjualan",
        t3_e4: "Varian Produk", t3_e5: "Integrasi Pengiriman", t3_e6: "Notifikasi Email",
        t3_e7: "Keamanan Tingkat Lanjut", t3_e8: "Dasbor Analitik", t3_e9: "Dukungan Prioritas", t3_e10: "10 Revisi",

        // FAQ
        faq_label: "Pertanyaan",
        faq_title: "Pertanyaan Umum",
        faq_desc: "Segala yang perlu Anda ketahui tentang proses, jadwal, dan hasil kerja kami.",
        faq_1_q: "Berapa lama waktu yang dibutuhkan untuk satu proyek?",
        faq_1_a: "Alur kerja lengkap kami biasanya membutuhkan waktu 8 hingga 12 minggu. Hal ini memastikan waktu yang cukup untuk riset yang teliti, desain piksel-sempurna, rekayasa yang kuat, dan pengujian QA di berbagai perangkat tanpa mengorbankan kualitas.",
        faq_2_q: "Apakah Anda bekerja dengan startup atau hanya perusahaan besar?",
        faq_2_a: "Kami berkolaborasi dengan keduanya. Baik Anda merupakan startup Seri-A yang ingin membangun kehadiran yang kuat maupun perusahaan besar yang mencari modernisasi arsitektur, solusi kami disesuaikan dengan kebutuhan struktural Anda.",
        faq_3_q: "Teknologi apa yang Anda gunakan?",
        faq_3_a: "Tumpukan utama kami untuk performa dan fleksibilitas adalah React (Next.js), Tailwind CSS, GSAP untuk animasi yang mengalir, dan solusi backend yang kuat seperti Node.js atau Laravel tergantung pada persyaratan API.",
        faq_4_q: "Dapatkah Anda mendesain ulang produk yang sudah ada?",
        faq_4_a: "Tentu. Kami sering mengaudit dan merombak platform lama, meningkatkan tingkat konversinya, retensi pengguna, dan keseluruhan estetika agar selaras dengan standar kemewahan modern.",

        // CTA
        cta_title_1: "Mari Bangun",
        cta_title_2: "Bersama",
        
        // Footer
        footer_desc: "Mengangkat kelas merek modern melalui desain dan arsitektur digital yang unggul.",
        footer_menu: "Menu",
        footer_socials: "Sosial",
        footer_location: "Lokasi",
        footer_loc_text: "Tim Remote Global<br>Beroperasi lintas zona waktu GMT ke PST.",
        footer_time: "Waktu Lokal:",
        footer_rights: "© 2026 DKS Studio. Hak cipta dilindungi.",
        footer_privacy: "Kebijakan Privasi",
        footer_terms: "Syarat dan Ketentuan"
    }
};
